// timer.js
// Pulse OS – Midnight compiler for FUNCTION_LOGS
// Supports .js and .html with correct insertion logic

import fs from "fs";
import path from "path";
import { getFirestore, Timestamp } from "firebase-admin/firestore";
import nodemailer from "nodemailer";

// -----------------------------
// CONFIG
// -----------------------------

const FUNCTION_LOGS_COLLECTION = "FUNCTION_LOGS";
const MIDNIGHT_WINDOW_MINUTES = 5;
const DEFAULT_PAGES_ROOT = path.join(process.cwd(), "pages");

// ----------------------------- I LOVE THIS ITS MY BEAUTY LOGGER EMAIL
// EMAIL TRANSPORT
// -----------------------------

function createMailer() {
  const SMTP_HOST = process.env.SMTP_HOST || "smtp.gmail.com";
  const SMTP_USER = process.env.SMTP_USER || process.env.EMAIL_USER;
  const SMTP_PASS = process.env.EMAIL_PASSWORD || process.env.SMTP_PASS;
  const ALERT_EMAIL_FROM =
    process.env.ALERT_EMAIL_FROM || `"Pulse OS" <no-reply@pulse.local>`;
  const ALERT_EMAIL_TO =
    process.env.ALERT_EMAIL_TO || "FordFamilyDelivery@gmail.com";

  if (!SMTP_USER || !SMTP_PASS) {
    console.warn("[timer.js] SMTP credentials missing – email disabled.");
    return null;
  }

  const transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: 465,
    secure: true,
    auth: { user: SMTP_USER, pass: SMTP_PASS }
  });

  return { transporter, from: ALERT_EMAIL_FROM, to: ALERT_EMAIL_TO };
}

// -----------------------------
// HELPERS
// -----------------------------

function deriveFilePathFromLog(log) {
  if (log.filePath) return log.filePath;

  const pagePath = log.pagePath || "/";
  const fileName = log.fileName || "index.js";

  const cleanPage = pagePath.replace(/^\/+/, "");
  return path.join(DEFAULT_PAGES_ROOT, cleanPage || "", fileName);
}

function groupLogs(logDocs) {
  const filesMap = new Map();

  for (const { id, data } of logDocs) {
    const log = data;
    const filePath = deriveFilePathFromLog(log);
    const pagePath = log.pagePath || "UNKNOWN_PAGE";
    const fnName = log.functionName || "unnamedFunction";

    if (!filesMap.has(filePath)) {
      filesMap.set(filePath, {
        pagePath,
        logs: [],
        functions: new Map()
      });
    }

    const fileEntry = filesMap.get(filePath);
    fileEntry.logs.push({ id, log });

    if (!fileEntry.functions.has(fnName)) {
      fileEntry.functions.set(fnName, {
        hasMissingFunction: false,
        fields: new Set()
      });
    }

    const fnEntry = fileEntry.functions.get(fnName);

    if (log.type === "missing_function") {
      fnEntry.hasMissingFunction = true;
    }

    if (log.type === "missing_field" && log.fieldName) {
      fnEntry.fields.add(log.fieldName);
    }
  }

  return filesMap;
}

function buildJSBlock(pagePath, filePath, functionsMap) {
  const now = new Date().toISOString();
  let block = "";

  block += "\n\n";
  block += "// #%#%#%#%#%#%#%#%#%#%#%#%#\n";
  block += "// # AUTO-GENERATED BY PULSE OS\n";
  block += `// # DATE: ${now}\n`;
  block += `// # PAGE: ${pagePath}\n`;
  block += `// # FILE: ${filePath}\n`;
  block += "// #%#%#%#%#%#%#%#%#%#%#%#%#\n\n";

  for (const [fnName, info] of functionsMap.entries()) {
    const fields = Array.from(info.fields);

    if (info.hasMissingFunction) {
      block += `// Auto-generated function stub for: ${fnName}\n`;
      block += `function ${fnName}() {\n`;
      if (fields.length > 0) {
        block += "  return {\n";
        for (const field of fields) {
          block += `    ${field}: null, // TODO auto-generated field\n`;
        }
        block += "  };\n";
      } else {
        block += "  return {};\n";
      }
      block += "}\n\n";
    } else if (fields.length > 0) {
      const helperName = `ensure_${fnName}_fields`;
      block += `// Auto-generated helper for: ${fnName}\n`;
      block += `function ${helperName}() {\n`;
      block += "  return {\n";
      for (const field of fields) {
        block += `    ${field}: null, // TODO auto-generated field\n`;
      }
      block += "  };\n";
      block += "}\n\n";
    }
  }

  block += "// #^#^#^#^#^#^#^#^#^#^#^#^#\n";
  block += "// # END AUTO-GENERATED BLOCK\n";
  block += "// #^#^#^#^#^#^#^#^#^#^#^#^#\n";

  return block;
}

function insertIntoHTML(original, block) {
  const lower = original.toLowerCase();

  const lastScriptIndex = lower.lastIndexOf("</script>");
  const lastBodyIndex = lower.lastIndexOf("</body>");

  if (lastScriptIndex !== -1 && lastScriptIndex > lastBodyIndex - 200) {
    return (
      original.slice(0, lastScriptIndex) +
      block +
      original.slice(lastScriptIndex)
    );
  }

  if (lastBodyIndex !== -1) {
    return (
      original.slice(0, lastBodyIndex) +
      `<script>${block}</script>\n` +
      original.slice(lastBodyIndex)
    );
  }

  return original + `<script>${block}</script>`;
}

function buildNewFilePath(originalPath) {
  const ext = path.extname(originalPath);
  const base = originalPath.slice(0, -ext.length);
  return `${base}-NEW${ext}`;
}

// -----------------------------
// FIRESTORE + FILE WRITING
// -----------------------------

async function fetchUnprocessedLogs(db) {
  const snap = await db
    .collection(FUNCTION_LOGS_COLLECTION)
    .where("processed", "==", false)
    .get();

  const docs = [];
  snap.forEach(doc => docs.push({ id: doc.id, data: doc.data() }));
  return docs;
}

async function processLogs(db) {
  const logs = await fetchUnprocessedLogs(db);
  if (!logs.length) return { generatedFiles: [] };

  const filesMap = groupLogs(logs);
  const generatedFiles = [];
  const batch = db.batch();
  const nowTs = Timestamp.now();

  for (const [filePath, entry] of filesMap.entries()) {
    try {
      const original = fs.readFileSync(filePath, "utf8");
      const ext = path.extname(filePath).toLowerCase();

      const jsBlock = buildJSBlock(
        entry.pagePath,
        filePath,
        entry.functions
      );

      let newContent =
        ext === ".html"
          ? insertIntoHTML(original, jsBlock)
          : original + jsBlock;

      const newFilePath = buildNewFilePath(filePath);

      fs.writeFileSync(newFilePath, newContent, "utf8");
      generatedFiles.push(newFilePath);

      for (const { id } of entry.logs) {
        const ref = db.collection(FUNCTION_LOGS_COLLECTION).doc(id);
        batch.update(ref, { processed: true, processedAt: nowTs });
      }
    } catch (err) {
      console.error("[timer.js] Failed to process:", filePath, err);
    }
  }

  await batch.commit();
  return { generatedFiles };
}

// -----------------------------
// EMAIL
// -----------------------------

async function sendEmail(mailer, files) {
  if (!mailer || !files.length) return;

  const subject = "Pulse OS – Auto-Generated Files Ready";
  const body = [
    "Pulse OS has generated new files:",
    "",
    ...files.map(f => ` - ${f}`),
    "",
    "Review the bottom of each file for the AUTO-GENERATED block."
  ].join("\n");

  await mailer.transporter.sendMail({
    from: mailer.from,
    to: mailer.to,
    subject,
    text: body
  });
}

// -----------------------------
// MIDNIGHT TIMER
// -----------------------------

export default function startPulseTimer() {
  const db = getFirestore();
  const mailer = createMailer();

  let lastRun = null;

  setInterval(async () => {
    const now = new Date();
    const today = now.toISOString().slice(0, 10);

    const inWindow =
      now.getHours() === 0 && now.getMinutes() < MIDNIGHT_WINDOW_MINUTES;

    if (!inWindow) return;
    if (lastRun === today) return;

    lastRun = today;

    const { generatedFiles } = await processLogs(db);
    await sendEmail(mailer, generatedFiles);
  }, 60 * 1000);
}